'use strict';
const root=document.getElementById('app');
const cfg=window.SERRE_CONFIG||{};
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const today=new Date();
const localMonth=()=>today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0');
const st={tab:'home',month:localMonth(),projects:[],milestones:[],weeks:[],focus:[],horizons:[],notes:[],user:null};
const monthDate=()=>st.month+'-01';
const monthName=()=>new Date(st.month+'-01T12:00:00').toLocaleDateString('fr-FR',{month:'long',year:'numeric'});
const project=id=>st.projects.find(p=>p.id===id);
const tint=p=>(p?.color_hex||'#809e87')+'22';
const tag=p=>'<span class="tag" style="--color:'+escapeHtml(p?.color_hex||'#56775c')+';--tint:'+tint(p)+'">'+escapeHtml(p?.icon_name||'🌱')+' '+escapeHtml(p?.name||'Projet')+'</span>';
const progress={planned:'Prévu',in_progress:'En cours',completed:'Terminé'};
const planning={reserve:'En réserve',selected:'Sélectionné',deferred:'Reporté'};
let db=null;
function configurationMissing(){root.innerHTML='<div class="wrap"><div class="card"><h2>🌱 Dernier branchement</h2><p>La Serre est publiée, mais ses paramètres publics Supabase ne sont pas encore renseignés.</p><p class="muted">Ajoute dans <code>config.js</code> l’URL Supabase et la clé publique anon/publishable de ton projet Hub writing. Aucun mot de passe ni secret.</p><p><a href="https://supabase.com/dashboard">Ouvrir Supabase</a></p></div></div>'}
async function getAll(){
 const names=['serre_projects','serre_milestones','serre_milestone_weeks','serre_month_focus','serre_horizons','serre_project_notes'];
 const results=await Promise.all(names.map(n=>db.from(n).select('*')));
 const bad=results.find(r=>r.error);
 if(bad)throw bad.error;
 [st.projects,st.milestones,st.weeks,st.focus,st.horizons,st.notes]=results.map(r=>r.data||[]);
 st.projects.sort((a,b)=>a.sort_order-b.sort_order||a.name.localeCompare(b.name));
}
async function reload(){try{await getAll();render()}catch(err){root.innerHTML='<div class="wrap"><div class="notice">Erreur de chargement : '+escapeHtml(err.message)+'</div><button class="btn" id="retry">Réessayer</button></div>';document.getElementById('retry').onclick=reload}}
async function persist(table,obj,id){const r=id?await db.from(table).update(obj).eq('id',id):await db.from(table).insert(obj);if(r.error)throw r.error;await reload()}
async function erase(table,id){const r=await db.from(table).delete().eq('id',id);if(r.error)throw r.error;await reload()}
function authView(){root.innerHTML='<section id="login" class="card"><h2>🌱 Bienvenue dans La Serre</h2><p class="muted">Connecte-toi avec ton compte Supabase habituel.</p><form id="sign"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Mot de passe<input type="password" name="password" autocomplete="current-password" required></label><button class="btn primary">Se connecter</button></form><p class="notice hidden" id="signErr"></p></section>';document.getElementById('sign').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);const r=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(r.error){const el=document.getElementById('signErr');el.textContent=r.error.message;el.classList.remove('hidden')}}}
function shell(content){root.innerHTML='<div class="wrap"><div class="sitebar"><div class="sitebrand"><strong>🌿 La Serre</strong><span>Chaque projet a son espace pour grandir.</span></div><nav class="nav" aria-label="Navigation"><button data-tab="home" class="'+(st.tab==='home'?'active':'')+'">Accueil</button><button data-tab="projects" class="'+(st.tab==='projects'?'active':'')+'">Projets</button><button data-tab="bloom" class="'+(st.tab==='bloom'?'active':'')+'">Floraison</button><button data-tab="admin" class="'+(st.tab==='admin'?'active':'')+'">Administration</button></nav><button class="btn small" id="logout">Sortir</button></div>'+content+'<p class="muted small" style="margin-top:38px;text-align:center">Les prévisions ne sont pas des promesses. 🌿</p></div><aside id="projectDrawer" class="drawer" aria-label="Détails du projet" aria-hidden="true"></aside><div id="drawerBackdrop" class="drawer-backdrop" hidden></div><dialog id="editorDialog"><div class="between"><h3 id="editorTitle"></h3><button class="btn small" id="closeDialog" aria-label="Fermer">✕</button></div><form id="editorForm"></form></dialog>';document.getElementById('logout').onclick=()=>db.auth.signOut();document.getElementById('drawerBackdrop').onclick=closeProjectDrawer;}
function closeProjectDrawer(){const d=document.getElementById('projectDrawer');const b=document.getElementById('drawerBackdrop');if(d){d.classList.remove('open');d.setAttribute('aria-hidden','true')}if(b)b.hidden=true}
function openProjectDrawer(id){const p=project(id);if(!p)return;const milestones=st.milestones.filter(m=>m.project_id===id).sort((a,b)=>a.target_month.localeCompare(b.target_month));const d=document.getElementById('projectDrawer');if(!d)return;d.innerHTML='<div class="between"><div>'+tag(p)+'<h2 style="margin:12px 0 0">Jalons du projet</h2></div><button class="btn small" data-action="closedrawer" aria-label="Fermer le panneau">✕</button></div><p class="muted small">Dépose les résultats attendus et leur mois cible. Floraison te permettra ensuite de choisir les semaines.</p><form id="quickMilestone" class="drawer-form">'+row('Résultat attendu *','title','','text','required maxlength="240"')+row('Mois cible','target_month',st.month,'month','required')+options('Planification','planning_status',Object.entries(planning),'reserve')+'<button class="btn primary" type="submit">+ Enregistrer le jalon</button></form><h3 style="margin-top:28px">Jalons enregistrés ('+milestones.length+')</h3>'+(milestones.length?milestones.map(m=>'<div class="drawer-item"><div><b>'+escapeHtml(m.title)+'</b><div class="muted small">'+escapeHtml(m.target_month.slice(0,7))+' · '+escapeHtml(planning[m.planning_status])+'</div></div><button class="btn small" data-action="editmilestone" data-id="'+m.id+'">Modifier</button></div>').join(''):'<div class="empty">Aucun jalon pour le moment.</div>');d.classList.add('open');d.setAttribute('aria-hidden','false');document.getElementById('drawerBackdrop').hidden=false;const form=document.getElementById('quickMilestone');form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);const btn=form.querySelector('[type=submit]');btn.disabled=true;try{const result=await db.from('serre_milestones').insert({project_id:id,title:String(f.get('title')).trim(),target_month:f.get('target_month')+'-01',planning_status:f.get('planning_status'),progress_status:'planned'});if(result.error)throw result.error;await getAll();render();openProjectDrawer(id)}catch(err){alert('Impossible de créer le jalon : '+err.message);btn.disabled=false}}}
function monthControls(){return '<div class="between"><button class="btn small" data-action="monthprev">←</button><b>'+escapeHtml(monthName())+'</b><button class="btn small" data-action="monthnext">→</button></div>'}
function milestoneView(m){return '<div class="item"><div>'+tag(project(m.project_id))+'<div style="margin-top:7px"><b>'+escapeHtml(m.title)+'</b></div><div class="muted small">'+escapeHtml(progress[m.progress_status]||'')+' · '+escapeHtml(planning[m.planning_status]||'')+(m.hard_deadline?' · Échéance ferme : '+escapeHtml(m.hard_deadline):'')+'</div></div><button class="btn small" data-action="editmilestone" data-id="'+m.id+'">Modifier</button></div>'}
function home(){const all=st.milestones.filter(m=>m.target_month===monthDate());const focus=st.focus.find(x=>x.month_start===monthDate());return '<div class="top"><div><div class="muted small">TABLEAU DE BORD MENSUEL</div><h2>'+escapeHtml(monthName())+'</h2></div>'+monthControls()+'</div><div class="focus"><div class="muted small">Projet à privilégier</div><div style="margin:12px 0">'+(focus?.project_id?tag(project(focus.project_id)):'<span class="muted">Aucun choix obligatoire ce mois-ci.</span>')+'</div><button class="btn small" data-action="focus">Choisir le cap</button></div><div class="stats"><div class="card"><div class="muted small">Sélectionnés</div><strong>'+all.filter(m=>m.planning_status==='selected').length+'</strong></div><div class="card"><div class="muted small">Accomplis</div><strong>'+all.filter(m=>m.progress_status==='completed').length+'</strong></div><div class="card"><div class="muted small">En réserve</div><strong>'+all.filter(m=>m.planning_status==='reserve').length+'</strong></div></div><div class="between"><h2>Jalons du mois</h2><span class="muted small">Création depuis Projets · répartition dans Floraison</span></div>'+(all.length?all.map(milestoneView).join(''):'<div class="empty">Une page blanche, pas une liste de retard. 🌱</div>')}
function projects(){return '<div class="between"><h2>Mes projets</h2><button class="btn primary" data-action="newproject">+ Projet</button></div><p class="muted">Ouvre un projet pour lui ajouter des jalons. Ils rejoindront ensuite Floraison et ton cockpit.</p><div class="cards">'+st.projects.map(p=>'<div class="card project" style="--color:'+escapeHtml(p.color_hex)+'"><h3>'+escapeHtml(p.icon_name||'🌱')+' '+escapeHtml(p.name)+'</h3><p class="muted">'+escapeHtml(p.description||'')+'</p><div class="between"><span class="muted small">'+escapeHtml({active:'Actif',paused:'En pause',archived:'Archivé'}[p.status]||'')+'</span><div class="between"><button class="btn primary small" data-action="openproject" data-id="'+p.id+'">Ouvrir les jalons</button><button class="btn small" data-action="editproject" data-id="'+p.id+'">Modifier</button></div></div></div>').join('')+'</div>'+(st.projects.length?'':'<div class="empty">Commençons par créer un premier projet coloré.</div>')}
function weekStarts(){const d=new Date(st.month+'-01T12:00:00'),end=new Date(d.getFullYear(),d.getMonth()+1,0,12);d.setDate(d.getDate()-(d.getDay()+6)%7);const v=[];while(d<=end){v.push(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'));d.setDate(d.getDate()+7)}return v}
function bloom(){const all=st.milestones.filter(m=>m.target_month===monthDate());return '<div class="top"><h2>Floraison</h2>'+monthControls()+'</div><p class="muted">Les semaines sont des repères facultatifs. Un jalon peut apparaître sur plusieurs semaines.</p>'+weekStarts().map(w=>{const items=all.filter(m=>st.weeks.some(x=>x.milestone_id===m.id&&x.week_start===w));return '<section class="week"><div class="between"><h3>Semaine du '+new Date(w+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long'})+'</h3><button class="btn small" data-action="placeweek" data-week="'+w+'">+ Placer</button></div>'+(items.length?items.map(m=>'<div class="item" style="--color:'+escapeHtml(project(m.project_id)?.color_hex||'#65886c')+'"><div>'+tag(project(m.project_id))+'<div><b>'+escapeHtml(m.title)+'</b></div></div><button class="btn small" data-action="unplaceweek" data-id="'+m.id+'" data-week="'+w+'">Retirer</button></div>').join(''):'<div class="muted small">Aucun jalon prévu, et c’est très bien.</div>')+'</section>'}).join('')}
function admin(){return '<h2>Administration</h2><div class="cards"><div class="card"><h3>Horizons trimestriels</h3><p class="muted">Un jalon peut exister sans horizon.</p><button class="btn" data-action="newhorizon">+ Horizon</button>'+st.horizons.map(h=>'<div class="item"><span>'+escapeHtml(h.title)+'<br><small class="muted">T'+h.quarter+' '+h.year+' · '+escapeHtml(project(h.project_id)?.name)+'</small></span><button class="btn small" data-action="edithorizon" data-id="'+h.id+'">Modifier</button></div>').join('')+'</div><div class="card"><h3>Post-it</h3><p class="muted">Des pistes à conserver, sans obligation.</p><button class="btn" data-action="newnote">+ Note</button>'+st.notes.map(n=>'<div class="item"><span>'+escapeHtml(n.title)+'<br><small class="muted">'+escapeHtml(project(n.project_id)?.name)+'</small></span><button class="btn small" data-action="editnote" data-id="'+n.id+'">Modifier</button></div>').join('')+'</div><div class="card"><h3>Sauvegarde</h3><p class="muted">Exporter les données de La Serre au format JSON.</p><button class="btn" data-action="export">Exporter</button></div></div>'}
function render(){if(!st.user)return authView();shell(({home,projects,bloom,admin})[st.tab]())}
function row(label,name,value='',type='text',required=''){return '<label>'+label+'<input type="'+type+'" name="'+name+'" value="'+escapeHtml(value)+'" '+required+'></label>'}
function options(label,name,opts,selected){return '<label>'+label+'<select name="'+name+'">'+opts.map(([v,t])=>'<option value="'+escapeHtml(v)+'" '+(String(v)===String(selected)?'selected':'')+'>'+escapeHtml(t)+'</option>').join('')+'</select></label>'}
function area(label,name,value=''){return '<label>'+label+'<textarea name="'+name+'">'+escapeHtml(value)+'</textarea></label>'}
function openEditor(title,fields,submit){document.getElementById('editorTitle').textContent=title;const form=document.getElementById('editorForm');form.innerHTML=fields+'<div class="between" style="margin-top:15px"><button type="button" class="btn" id="cancelEditor">Annuler</button><button class="btn primary" type="submit">Enregistrer</button></div>';document.getElementById('cancelEditor').onclick=()=>document.getElementById('editorDialog').close();document.getElementById('closeDialog').onclick=()=>document.getElementById('editorDialog').close();form.onsubmit=async e=>{e.preventDefault();let button=form.querySelector('[type=submit]');button.disabled=true;try{await submit(new FormData(form));document.getElementById('editorDialog').close()}catch(e){alert('Impossible de sauvegarder : '+e.message)}finally{button.disabled=false}};document.getElementById('editorDialog').showModal()}
function projectEditor(id){const p=project(id);openEditor(p?'Modifier le projet':'Créer un projet',row('Nom *','name',p?.name||'','text','required maxlength="160"')+row('Couleur','color_hex',p?.color_hex||'#C4B3E8','color')+row('Icône (emoji)','icon_name',p?.icon_name||'🌱')+options('Statut','status',[['active','Actif'],['paused','En pause'],['archived','Archivé']],p?.status||'active')+area('Description','description',p?.description||''),async f=>persist('serre_projects',{name:f.get('name').trim(),color_hex:f.get('color_hex'),icon_name:f.get('icon_name')||'🌱',status:f.get('status'),description:f.get('description')},id))}
function milestoneEditor(id){if(!st.projects.length){alert('Commence par créer un projet dans l’onglet Projets.');return}const m=st.milestones.find(x=>x.id===id);const chosen=m?.project_id||st.projects[0].id;const hs=[['','Sans horizon'],...st.horizons.filter(h=>h.project_id===chosen).map(h=>[h.id,h.title])];openEditor(m?'Modifier le jalon':'Créer un jalon',row('Résultat attendu *','title',m?.title||'','text','required')+options('Projet','project_id',st.projects.map(p=>[p.id,p.name]),chosen)+options('Horizon facultatif','horizon_id',hs,m?.horizon_id||'')+row('Mois cible','target_month',(m?.target_month||monthDate()).slice(0,7),'month','required')+row('Vraie échéance (facultative)','hard_deadline',m?.hard_deadline||'','date')+options('Planification','planning_status',Object.entries(planning),m?.planning_status||'reserve')+options('Avancement','progress_status',Object.entries(progress),m?.progress_status||'planned')+area('Notes','details',m?.details||''),async f=>{const project_id=f.get('project_id'),horizon_id=f.get('horizon_id')||null;if(horizon_id&&!st.horizons.some(h=>h.id===horizon_id&&h.project_id===project_id))throw Error('L’horizon doit appartenir au projet sélectionné.');const status=f.get('progress_status');await persist('serre_milestones',{project_id,horizon_id,title:f.get('title').trim(),target_month:f.get('target_month')+'-01',hard_deadline:f.get('hard_deadline')||null,planning_status:f.get('planning_status'),progress_status:status,completed_at:status==='completed'?(m?.completed_at||new Date().toISOString()):null,details:f.get('details')},id)});const ps=document.querySelector('[name=project_id]');ps.onchange=()=>{const field=document.querySelector('[name=horizon_id]');field.innerHTML='<option value="">Sans horizon</option>'+st.horizons.filter(h=>h.project_id===ps.value).map(h=>'<option value="'+escapeHtml(h.id)+'">'+escapeHtml(h.title)+'</option>').join('')}}
function focusEditor(){const old=st.focus.find(f=>f.month_start===monthDate());openEditor('Cap du mois',options('Projet à privilégier','project_id',[['','Aucun'],...st.projects.map(p=>[p.id,p.name])],old?.project_id||'')+area('Note du mois','focus_note',old?.focus_note||''),async f=>persist('serre_month_focus',{month_start:monthDate(),project_id:f.get('project_id')||null,focus_note:f.get('focus_note')},old?.id))}
function horizonEditor(id){if(!st.projects.length)return alert('Crée d’abord un projet.');const h=st.horizons.find(x=>x.id===id);openEditor('Horizon trimestriel',row('Intitulé *','title',h?.title||'','text','required')+options('Projet','project_id',st.projects.map(p=>[p.id,p.name]),h?.project_id||st.projects[0].id)+row('Année','year',h?.year||new Date().getFullYear(),'number','required min="2020" max="2100"')+options('Trimestre','quarter',[[1,'T1'],[2,'T2'],[3,'T3'],[4,'T4']],h?.quarter||1)+area('Résultat souhaité','desired_outcome',h?.desired_outcome||''),async f=>persist('serre_horizons',{title:f.get('title').trim(),project_id:f.get('project_id'),year:Number(f.get('year')),quarter:Number(f.get('quarter')),desired_outcome:f.get('desired_outcome')},id))}
function noteEditor(id){if(!st.projects.length)return alert('Crée d’abord un projet.');const n=st.notes.find(x=>x.id===id);openEditor('Post-it',row('Titre *','title',n?.title||'','text','required')+options('Projet','project_id',st.projects.map(p=>[p.id,p.name]),n?.project_id||st.projects[0].id)+area('Idée','body',n?.body||''),async f=>persist('serre_project_notes',{title:f.get('title').trim(),project_id:f.get('project_id'),body:f.get('body')},id))}
function placeWeek(w){const choices=st.milestones.filter(m=>m.target_month===monthDate()&&!st.weeks.some(x=>x.milestone_id===m.id&&x.week_start===w));if(!choices.length)return alert('Ajoute un jalon disponible pour ce mois.');openEditor('Placer un jalon',options('Jalon','milestone_id',choices.map(m=>[m.id,m.title]),choices[0].id),async f=>persist('serre_milestone_weeks',{milestone_id:f.get('milestone_id'),week_start:w}))}
function exportJson(){const o={exported_at:new Date().toISOString(),projects:st.projects,milestones:st.milestones,weeks:st.weeks,focus:st.focus,horizons:st.horizons,notes:st.notes};const url=URL.createObjectURL(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='la-serre-'+st.month+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',async e=>{const tab=e.target.closest('[data-tab]');if(tab){closeProjectDrawer();st.tab=tab.dataset.tab;render();return}const b=e.target.closest('[data-action]');if(!b)return;try{switch(b.dataset.action){case'monthprev':case'monthnext':{const d=new Date(st.month+'-01T12:00:00');d.setMonth(d.getMonth()+(b.dataset.action==='monthprev'?-1:1));st.month=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');render();break}case'newproject':projectEditor();break;case'openproject':openProjectDrawer(b.dataset.id);break;case'closedrawer':closeProjectDrawer();break;case'editproject':projectEditor(b.dataset.id);break;case'newmilestone':milestoneEditor();break;case'editmilestone':closeProjectDrawer();milestoneEditor(b.dataset.id);break;case'focus':focusEditor();break;case'newhorizon':horizonEditor();break;case'edithorizon':horizonEditor(b.dataset.id);break;case'newnote':noteEditor();break;case'editnote':noteEditor(b.dataset.id);break;case'placeweek':placeWeek(b.dataset.week);break;case'unplaceweek':{const w=st.weeks.find(x=>x.milestone_id===b.dataset.id&&x.week_start===b.dataset.week);if(w)await erase('serre_milestone_weeks',w.id);break}case'export':exportJson();break}}catch(err){alert(err.message)}});
async function init(){if(!cfg.supabaseUrl||!cfg.supabaseAnonKey||!window.supabase){configurationMissing();return}db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);db.auth.onAuthStateChange((event,session)=>{setTimeout(async()=>{const old=st.user?.id;st.user=session?.user||null;if(st.user){if(st.user.id!==old)await reload()}else authView()},0)});const r=await db.auth.getSession();if(r.error){root.textContent=r.error.message;return}st.user=r.data.session?.user||null;if(st.user)await reload();else authView()}
init();
